package sk.uniza.fri.zts_semestralnapraca.suites;

// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import sk.uniza.fri.zts_semestralnapraca.ParentTest;

public class PagesizeTest extends ParentTest {

    @Test
    public void pagesizebikeLIST() {
        driver.get("https://motocykle.bazos.sk/?gal=l");
        driver.manage().window().setSize(new Dimension(989, 666));
        driver.findElement(By.cssSelector(".inzeraty:nth-child(5) .nadpis > a")).click();
        driver.navigate().back();
        closeCookiesIfNeeded();
        waitAndClick(".inzeraty:nth-child(24) .nadpis > a");
    }

    @Test
    public void pagesizebikeTILES() {
        driver.get("https://motocykle.bazos.sk/?gal=g");
        driver.manage().window().setSize(new Dimension(989, 666));
        driver.findElement(By.cssSelector(".galleryobal:nth-child(1) > .gallerytxt > a")).click();
        driver.navigate().back();
        closeCookiesIfNeeded();
        waitAndClick(".inzeraty:nth-child(60) .nadpis > a");
    }

    @Test
    public void pagesizepcLIST() {
        driver.get("https://pc.bazos.sk/?gal=l");
        driver.manage().window().setSize(new Dimension(989, 666));
        driver.findElement(By.cssSelector(".inzeraty:nth-child(5) .nadpis > a")).click();
        driver.navigate().back();
        closeCookiesIfNeeded();
        waitAndClick(".inzeraty:nth-child(24) .nadpis > a");
    }

    @Test
    public void pagesizepcTILES() {
        driver.get("https://pc.bazos.sk/?gal=g");
        driver.manage().window().setSize(new Dimension(989, 666));
        driver.findElement(By.cssSelector(".galleryobal:nth-child(1) > .gallerytxt > a")).click();
        driver.navigate().back();
        closeCookiesIfNeeded();
        waitAndClick(".inzeraty:nth-child(60) .nadpis > a");
    }

    @Test
    public void pagesizerealestateLIST() {
        driver.get("https://reality.bazos.sk/?gal=l");
        driver.manage().window().setSize(new Dimension(989, 666));
        driver.findElement(By.cssSelector(".inzeraty:nth-child(5) .nadpis > a")).click();
        driver.navigate().back();
        closeCookiesIfNeeded();
        waitAndClick(".inzeraty:nth-child(24) .nadpis > a");
    }

    @Test
    public void pagesizerealestateTILES() {
        driver.get("https://reality.bazos.sk/?gal=g");
        driver.manage().window().setSize(new Dimension(989, 666));
        driver.findElement(By.cssSelector(".galleryobal:nth-child(1) > .gallerytxt > a")).click();
        driver.navigate().back();
        closeCookiesIfNeeded();
        waitAndClick(".inzeraty:nth-child(60) .nadpis > a");
    }
}
