package sk.uniza.fri.zts_semestralnapraca.suites;

// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.NoSuchElementException;
import sk.uniza.fri.zts_semestralnapraca.ParentTest;

public class SearchTest extends ParentTest {

    @Test
    public void searchOfExisting() {
        driver.get("https://www.bazos.sk/");
        driver.findElement(By.id("hledat")).sendKeys("pes");
        driver.findElement(By.name("Submit")).click();
        driver.findElement(By.cssSelector(".inzeraty:nth-child(5) .nadpis > a")).click();
    }

    @Test
    public void searchOfNotExisting() {
        driver.get("https://www.bazos.sk/");
        driver.findElement(By.id("hledat")).sendKeys("pes s dáždnikom");
        driver.findElement(By.name("Submit")).click();
        try {
            driver.findElement(By.cssSelector(".inzeraty:nth-child(5) .nadpis > a")).click();
        } catch (NoSuchElementException ex) {
            //element not found, website is empty
        }
    }
}
