package sk.uniza.fri.zts_semestralnapraca.suites;

// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import sk.uniza.fri.zts_semestralnapraca.ParentTest;

import java.time.Duration;

import static org.junit.Assert.assertEquals;

public class TranslationTest extends ParentTest {

    private void closeCookiesIfNeeded() {
        try {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(2));
            wait.until(ExpectedConditions.visibilityOfElementLocated(
                    By.xpath("//button[contains(text(),'Súhlasím')]")
                    )
            );
            driver.findElement(By.xpath("//button[contains(text(),'Súhlasím')]"))
                    .click();

        } catch (NoSuchElementException ex) {
            //cookies already accepted
            System.out.println();
        }
    }

    @Test
    public void translationaustria() {
        closeCookiesIfNeeded();
        driver.findElement(By.linkText("Rakúsko")).click();
        vars.put("pridat_text", driver.findElement(By.cssSelector(".pridati")).getText());
        assertEquals(vars.get("pridat_text").toString(), "Anzeige aufgeben");
    }

    @Test
    public void translationczech() {
        closeCookiesIfNeeded();
        driver.findElement(By.linkText("Česká republika")).click();
        vars.put("pridat_text", driver.findElement(By.cssSelector(".pridati")).getText());
        assertEquals(vars.get("pridat_text").toString(), "Přidat inzerát");
    }

    @Test
    public void translationpolish() {
        closeCookiesIfNeeded();
        driver.findElement(By.linkText("Poľsko")).click();
        vars.put("pridat_text", driver.findElement(By.cssSelector(".pridati")).getText());
        assertEquals(vars.get("pridat_text").toString(), "Dodaj darmowe ogłoszenie");
    }

}
