package sk.uniza.fri.zts_semestralnapraca.suites;

// Generated by Selenium IDE

import org.junit.Test;
import org.openqa.selenium.By;
import sk.uniza.fri.zts_semestralnapraca.ParentTest;

import static org.junit.Assert.assertEquals;

public class TranslationTest extends ParentTest {

    @Test
    public void translationaustria() {
        driver.get("https://www.bazos.sk/");
        closeCookiesIfNeeded();
        driver.findElement(By.linkText("Rakúsko")).click();
        vars.put("pridat_text", driver.findElement(By.cssSelector(".pridati")).getText());
        assertEquals(vars.get("pridat_text").toString(), "Anzeige aufgeben");
    }

    @Test
    public void translationczech() {
        driver.get("https://www.bazos.sk/");
        closeCookiesIfNeeded();
        driver.findElement(By.linkText("Česká republika")).click();
        vars.put("pridat_text", driver.findElement(By.cssSelector(".pridati")).getText());
        assertEquals(vars.get("pridat_text").toString(), "Přidat inzerát");
    }

    @Test
    public void translationpolish() {
        driver.get("https://www.bazos.sk/");
        closeCookiesIfNeeded();
        driver.findElement(By.linkText("Poľsko")).click();
        vars.put("pridat_text", driver.findElement(By.cssSelector(".pridati")).getText());
        assertEquals(vars.get("pridat_text").toString(), "Dodaj darmowe ogłoszenie");
    }

}
